import { faker } from '@faker-js/faker'

export const createResolvers = (perfil, patrones) => [
    // Autenticación
    { test: patrones.confirmPassword, value: () => perfil.password },
    { test: patrones.currentPassword, value: () => perfil.password },
    { test: patrones.newPassword, value: () => faker.internet.password({ length: 12 }) },
    { test: patrones.email, value: () => perfil.email },
    { test: patrones.password, value: () => perfil.password },
    { test: patrones.username, value: () => perfil.username },
    { test: patrones.login, value: () => perfil.username },
    { test: patrones.logout, value: () => null },
    { test: patrones.register, value: () => true },
    { test: patrones.rememberMe, value: () => faker.datatype.boolean() },
    { test: patrones.forgotPassword, value: () => faker.internet.email() },
    { test: patrones.resetToken, value: () => faker.string.alphanumeric(32).toUpperCase() },
    { test: patrones.otp, value: () => faker.string.numeric(6) },
    { test: patrones.totp, value: () => faker.string.alphanumeric(16).toUpperCase() },
    { test: patrones.backupCode, value: () => faker.string.alphanumeric(10).toUpperCase() },
    { test: patrones.sessionId, value: () => faker.string.uuid() },
    { test: patrones.authToken, value: () => faker.string.uuid() },
    { test: patrones.apiKey, value: () => faker.string.alphanumeric(32).toUpperCase() },
    { test: patrones.accessToken, value: () => faker.string.uuid() },
    { test: patrones.refreshToken, value: () => faker.string.uuid() },
    { test: patrones.captcha, value: () => "validado" },
    { test: patrones.securityQuestion, value: () => faker.helpers.arrayElement([
        "¿Cuál es el nombre de tu primera mascota?",
        "¿Cuál es tu comida favorita?",
        "¿En qué ciudad naciste?",
        "¿Cuál es el nombre de tu madre?",
        "¿Cuál es tu libro favorito?"
    ]) },
    { test: patrones.securityAnswer, value: () => faker.lorem.word() },
    { test: patrones.mfaCode, value: () => faker.string.numeric(6) },
    { test: patrones.pinCode, value: () => faker.string.numeric(4) },
    
    // Datos Personales
    { test: patrones.fullName, value: () => `${perfil.firstName} ${perfil.lastName}` },
    { test: patrones.firstName, value: () => perfil.firstName },
    { test: patrones.lastName, value: () => perfil.lastName },
    { test: patrones.middleName, value: () => faker.person.middleName() },
    { test: patrones.nickname, value: () => perfil.username },
    { test: patrones.maidenName, value: () => faker.person.lastName() },
    { test: patrones.prefix, value: () => faker.helpers.arrayElement(['Sr.', 'Sra.', 'Srta.', 'Dr.', 'Prof.']) },
    { test: patrones.suffix, value: () => faker.helpers.arrayElement(['Jr.', 'Sr.', 'II', 'III', 'PhD']) },
    { test: patrones.gender, value: () => faker.person.sex() },
    { test: patrones.pronouns, value: () => faker.helpers.arrayElement(['él/él', 'ella/ella', 'elle/elle']) },
    { test: patrones.birthDate, value: () => perfil.birthDate.toISOString().split("T")[0] },
    { test: patrones.birthPlace, value: () => `${faker.location.city()}, ${faker.location.country()}` },
    { test: patrones.age, value: () => faker.number.int({ min: 18, max: 80 }) },
    { test: patrones.zodiac, value: () => faker.helpers.arrayElement([
        'Aries', 'Tauro', 'Géminis', 'Cáncer', 'Leo', 'Virgo',
        'Libra', 'Escorpio', 'Sagitario', 'Capricornio', 'Acuario', 'Piscis'
    ]) },
    { test: patrones.bloodType, value: () => faker.helpers.arrayElement(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']) },
    { test: patrones.height, value: () => `${faker.number.int({ min: 150, max: 200 })} cm` },
    { test: patrones.weight, value: () => `${faker.number.int({ min: 50, max: 100 })} kg` },
    { test: patrones.hairColor, value: () => faker.helpers.arrayElement(['Negro', 'Castaño', 'Rubio', 'Pelirrojo', 'Canoso']) },
    { test: patrones.eyeColor, value: () => faker.helpers.arrayElement(['Marrón', 'Azul', 'Verde', 'Avellana', 'Gris']) },
    { test: patrones.skinTone, value: () => faker.helpers.arrayElement(['Blanco', 'Moreno', 'Negro', 'Oliva', 'Claro']) },
    { test: patrones.ethnicity, value: () => faker.helpers.arrayElement(['Hispano', 'Caucásico', 'Afroamericano', 'Asiático', 'Indígena']) },
    { test: patrones.nationality, value: () => faker.location.country() },
    { test: patrones.maritalStatus, value: () => faker.helpers.arrayElement(['Soltero/a', 'Casado/a', 'Divorciado/a', 'Viudo/a', 'Separado/a']) },
    { test: patrones.spouseName, value: () => faker.person.fullName() },
    { test: patrones.numberOfChildren, value: () => faker.number.int({ min: 0, max: 5 }) },
    { test: patrones.occupation, value: () => faker.person.jobTitle() },
    { test: patrones.income, value: () => faker.finance.amount({ min: 20000, max: 150000, dec: 0 }) },
    { test: patrones.education, value: () => faker.helpers.arrayElement(['Primaria', 'Secundaria', 'Universitario', 'Postgrado', 'Maestría', 'Doctorado']) },
    { test: patrones.degree, value: () => faker.helpers.arrayElement(['Licenciatura', 'Ingeniería', 'Maestría', 'Doctorado', 'Diplomatura']) },
    { test: patrones.university, value: () => faker.company.name() + ' University' },
    { test: patrones.graduationYear, value: () => faker.date.past({ years: 20 }).getFullYear() },
    { test: patrones.skills, value: () => faker.helpers.arrayElements(['JavaScript', 'Python', 'Java', 'Diseño', 'Marketing', 'Ventas'], 3).join(', ') },
    { test: patrones.languages, value: () => faker.helpers.arrayElements(['Español', 'Inglés', 'Francés', 'Alemán', 'Italiano', 'Portugués'], 2).join(', ') },
    { test: patrones.militaryService, value: () => faker.helpers.arrayElement(['Sí', 'No', 'Exento']) },
    { test: patrones.religion, value: () => faker.helpers.arrayElement(['Católica', 'Cristiana', 'Judía', 'Musulmana', 'Budista', 'Hindú', 'Atea']) },
    { test: patrones.politicalViews, value: () => faker.helpers.arrayElement(['Izquierda', 'Centro', 'Derecha', 'Progresista', 'Conservador', 'Moderado']) },
    { test: patrones.personalityType, value: () => faker.helpers.arrayElement(['INTJ', 'INTP', 'ENTJ', 'ENTP', 'INFJ', 'INFP', 'ENFJ', 'ENFP']) },
    { test: patrones.hobbies, value: () => faker.helpers.arrayElements(['Leer', 'Viajar', 'Cocinar', 'Deportes', 'Música', 'Cine'], 3).join(', ') },
    { test: patrones.favoriteColor, value: () => faker.color.human() },
    { test: patrones.favoriteFood, value: () => faker.helpers.arrayElement(['Pizza', 'Sushi', 'Pasta', 'Ensalada', 'Hamburguesa', 'Tacos']) },
    { test: patrones.favoriteMusic, value: () => faker.helpers.arrayElement(['Rock', 'Pop', 'Jazz', 'Clásica', 'Electrónica', 'Reggaetón']) },
    { test: patrones.favoriteMovie, value: () => faker.helpers.arrayElement(['El Padrino', 'Titanic', 'Star Wars', 'Avatar', 'Matrix', 'Interestelar']) },
    { test: patrones.favoriteBook, value: () => faker.helpers.arrayElement(['Cien años de soledad', 'Don Quijote', '1984', 'El Principito', 'Rayuela']) },
    { test: patrones.favoriteSport, value: () => faker.helpers.arrayElement(['Fútbol', 'Baloncesto', 'Tenis', 'Natación', 'Ciclismo', 'Running']) },
    { test: patrones.petName, value: () => faker.person.firstName() },
    { test: patrones.petType, value: () => faker.helpers.arrayElement(['Perro', 'Gato', 'Pájaro', 'Pez', 'Conejo', 'Hámster']) },
    { test: patrones.numberOfPets, value: () => faker.number.int({ min: 0, max: 3 }) },
    { test: patrones.drivingLicense, value: () => faker.helpers.arrayElement(['Clase A', 'Clase B', 'Clase C', 'Internacional']) },
    { test: patrones.passportNumber, value: () => faker.string.alphanumeric(9).toUpperCase() },
    { test: patrones.nationalId, value: () => faker.string.numeric(8) + faker.string.alpha(1).toUpperCase() },
    { test: patrones.taxId, value: () => faker.string.numeric(9) },
    { test: patrones.socialSecurity, value: () => faker.string.numeric(9) },
    
    // Contacto
    { test: patrones.phone, value: () => perfil.phone },
    { test: patrones.mobile, value: () => faker.phone.number() },
    { test: patrones.homePhone, value: () => faker.phone.number() },
    { test: patrones.workPhone, value: () => faker.phone.number() },
    { test: patrones.fax, value: () => faker.phone.number() },
    { test: patrones.pager, value: () => faker.phone.number() },
    { test: patrones.whatsapp, value: () => faker.phone.number() },
    { test: patrones.telegram, value: () => perfil.username },
    { test: patrones.signal, value: () => perfil.username },
    { test: patrones.wechat, value: () => perfil.username },
    { test: patrones.line, value: () => perfil.username },
    { test: patrones.viber, value: () => faker.phone.number() },
    { test: patrones.discord, value: () => perfil.username + '#1234' },
    { test: patrones.slack, value: () => perfil.username },
    { test: patrones.zoom, value: () => perfil.username },
    { test: patrones.teams, value: () => perfil.username },
    { test: patrones.skype, value: () => perfil.username },
    { test: patrones.snapchat, value: () => perfil.username },
    { test: patrones.tiktok, value: () => '@' + perfil.username },
    
    // Redes Sociales
    { test: patrones.twitter, value: () => '@' + perfil.username },
    { test: patrones.facebook, value: () => `https://facebook.com/${perfil.username}` },
    { test: patrones.instagram, value: () => '@' + perfil.username },
    { test: patrones.linkedin, value: () => `https://linkedin.com/in/${perfil.username}` },
    { test: patrones.github, value: () => `https://github.com/${perfil.username}` },
    { test: patrones.gitlab, value: () => `https://gitlab.com/${perfil.username}` },
    { test: patrones.bitbucket, value: () => `https://bitbucket.org/${perfil.username}` },
    { test: patrones.youtube, value: () => `https://youtube.com/@${perfil.username}` },
    { test: patrones.twitch, value: () => `https://twitch.tv/${perfil.username}` },
    { test: patrones.pinterest, value: () => `https://pinterest.com/${perfil.username}` },
    { test: patrones.tumblr, value: () => `https://${perfil.username}.tumblr.com` },
    { test: patrones.reddit, value: () => `u/${perfil.username}` },
    { test: patrones.medium, value: () => `https://medium.com/@${perfil.username}` },
    { test: patrones.devto, value: () => `https://dev.to/${perfil.username}` },
    { test: patrones.hashnode, value: () => `https://hashnode.com/@${perfil.username}` },
    { test: patrones.substack, value: () => `https://${perfil.username}.substack.com` },
    { test: patrones.patreon, value: () => `https://patreon.com/${perfil.username}` },
    { test: patrones.onlyfans, value: () => `https://onlyfans.com/${perfil.username}` },
    { test: patrones.fansly, value: () => `https://fansly.com/${perfil.username}` },
    { test: patrones.tinder, value: () => perfil.firstName },
    { test: patrones.bumble, value: () => perfil.firstName },
    { test: patrones.hinge, value: () => perfil.firstName },
    { test: patrones.myspace, value: () => `https://myspace.com/${perfil.username}` },
    { test: patrones.flickr, value: () => `https://flickr.com/people/${perfil.username}` },
    { test: patrones.imgur, value: () => `https://imgur.com/user/${perfil.username}` },
    { test: patrones.behance, value: () => `https://behance.net/${perfil.username}` },
    { test: patrones.dribbble, value: () => `https://dribbble.com/${perfil.username}` },
    { test: patrones.angelList, value: () => `https://angel.co/u/${perfil.username}` },
    { test: patrones.productHunt, value: () => `https://producthunt.com/@${perfil.username}` },
    { test: patrones.threadless, value: () => `https://threadless.com/@${perfil.username}` },
    { test: patrones.vimeo, value: () => `https://vimeo.com/${perfil.username}` },
    { test: patrones.dailymotion, value: () => `https://dailymotion.com/${perfil.username}` },
    
    // Dirección
    { test: patrones.address, value: () => perfil.address },
    { test: patrones.addressLine1, value: () => faker.location.streetAddress() },
    { test: patrones.addressLine2, value: () => faker.location.secondaryAddress() },
    { test: patrones.street, value: () => faker.location.street() },
    { test: patrones.streetNumber, value: () => faker.location.buildingNumber() },
    { test: patrones.building, value: () => faker.helpers.arrayElement(['Edificio A', 'Torre B', 'Complejo C', 'Bloque 1']) },
    { test: patrones.apartment, value: () => `Apt ${faker.number.int({ min: 1, max: 50 })}` },
    { test: patrones.floor, value: () => `Piso ${faker.number.int({ min: 1, max: 20 })}` },
    { test: patrones.door, value: () => `Puerta ${faker.string.alphanumeric(1).toUpperCase()}` },
    { test: patrones.city, value: () => faker.location.city() },
    { test: patrones.state, value: () => faker.location.state() },
    { test: patrones.country, value: () => faker.location.country() },
    { test: patrones.zipCode, value: () => faker.location.zipCode() },
    { test: patrones.neighborhood, value: () => faker.location.county() },
    { test: patrones.county, value: () => faker.location.county() },
    { test: patrones.municipality, value: () => faker.location.city() },
    { test: patrones.coordinates, value: () => `${faker.location.latitude()}, ${faker.location.longitude()}` },
    { test: patrones.latitude, value: () => faker.location.latitude() },
    { test: patrones.longitude, value: () => faker.location.longitude() },
    { test: patrones.timezone, value: () => faker.location.timeZone() },
    { test: patrones.plusCode, value: () => faker.location.zipCode() + '+' + faker.string.alphanumeric(2).toUpperCase() },
    { test: patrones.what3words, value: () => faker.lorem.words(3).replace(/ /g, '.') },
    
    // Trabajo y Educación
    { test: patrones.company, value: () => faker.company.name() },
    { test: patrones.jobTitle, value: () => faker.person.jobTitle() },
    { test: patrones.department, value: () => faker.commerce.department() },
    { test: patrones.employeeId, value: () => faker.string.alphanumeric(8).toUpperCase() },
    { test: patrones.manager, value: () => faker.person.fullName() },
    { test: patrones.workEmail, value: () => faker.internet.email({ firstName: perfil.firstName, lastName: perfil.lastName, provider: faker.company.name().toLowerCase().replace(/\s/g, '') + '.com' }) },
    { test: patrones.workPhone, value: () => faker.phone.number() },
    { test: patrones.workAddress, value: () => faker.location.streetAddress() },
    { test: patrones.startDate, value: () => faker.date.past().toISOString().split("T")[0] },
    { test: patrones.endDate, value: () => faker.date.future().toISOString().split("T")[0] },
    { test: patrones.hireDate, value: () => faker.date.past({ years: 10 }).toISOString().split("T")[0] },
    { test: patrones.terminationDate, value: () => faker.date.recent().toISOString().split("T")[0] },
    { test: patrones.yearsExperience, value: () => faker.number.int({ min: 1, max: 30 }) },
    { test: patrones.skills, value: () => faker.helpers.arrayElements(['JavaScript', 'Python', 'Java', 'Gestión', 'Ventas', 'Marketing'], 3).join(', ') },
    { test: patrones.certifications, value: () => faker.helpers.arrayElements(['AWS', 'PMP', 'Scrum', 'ITIL', 'CPA'], 2).join(', ') },
    { test: patrones.languages, value: () => faker.helpers.arrayElements(['Español nativo', 'Inglés avanzado', 'Francés básico'], 2).join(', ') },
    { test: patrones.education, value: () => faker.helpers.arrayElement(['Primaria', 'Secundaria', 'Universitario', 'Postgrado', 'Maestría', 'Doctorado']) },
    { test: patrones.degree, value: () => faker.helpers.arrayElement(['Licenciatura', 'Ingeniería', 'Maestría', 'Doctorado', 'Diplomatura']) },
    { test: patrones.fieldOfStudy, value: () => faker.helpers.arrayElement(['Ingeniería', 'Medicina', 'Derecho', 'Administración', 'Arquitectura']) },
    { test: patrones.institution, value: () => faker.company.name() + ' University' },
    { test: patrones.graduationDate, value: () => faker.date.past({ years: 15 }).toISOString().split("T")[0] },
    { test: patrones.gpa, value: () => faker.number.float({ min: 2.0, max: 4.0, precision: 0.1 }) },
    { test: patrones.honors, value: () => faker.helpers.arrayElement(['Cum Laude', 'Magna Cum Laude', 'Summa Cum Laude', 'Ninguno']) },
    { test: patrones.thesisTitle, value: () => faker.lorem.sentence({ min: 3, max: 6 }) },
    { test: patrones.advisor, value: () => faker.person.fullName() }
]